"""final_drift_check

Revision ID: 9d21d3371007
Revises: de0dd22157d3
Create Date: 2025-12-17 18:30:51.940065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d21d3371007'
down_revision = 'de0dd22157d3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_applications_search_gin', table_name='applications', postgresql_using='gin')
    op.create_index('idx_applications_search_gin', 'applications', [sa.text("to_tsvector('english', company_name || ' ' || job_title || ' ' || COALESCE(notes, ''))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_applications_search_gin', table_name='applications', postgresql_using='gin')
    op.create_index('idx_applications_search_gin', 'applications', [sa.text("to_tsvector('english'::regconfig, (((company_name::text || ' '::text) || job_title::text) || ' '::text) || COALESCE(notes, ''::text))")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

